### ISSUE TITLE
Class referenced in the layout file, `me.zhanghai.android.materialprogressbar.MaterialProgressBar`, was not found in the project or the libraries

### ISSUE THREAD

**Issue by Ethosan** [thiagojacinto/pomodoro-android-java-app#2]
Hi, where can I find/add this "me.zhanghai.android.materialprogressbar.MaterialProgressBar". Thank you!

**Comment by thiagojacinto** [comment]
Hello there @Ethosan , have you tried this lib's documentation?
> https://github.com/zhanghai/MaterialProgressBar
